[tool.poetry]
name = "mcp9808"
version = "0.1.0"
description = ""
authors = ["Jacob Zarnstorff"]

[tool.poetry.dependencies]
python = "^3.9"
smbus2 = "^0.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
